# Linking the Mobility Report data

In [1]:
import matplotlib.pyplot as plt 
%matplotlib inline
import pandas as pd
import numpy as np
from IPython import display

In [2]:
import os
list_files = os.listdir()  # List of files in current directory

import re
files_desired = []

# Loop for obtaining the specific files with the desired information
for file in list_files:
    result = re.findall('[0-9A-Za-z()_]*_ES_Region_Mobility_[0-9A-Za-z()_]*.csv$', file)
    if result:
        result = ''.join(result)
        files_desired.append(result)
        
files_desired

['2020_ES_Region_Mobility_Report.csv',
 '2021_ES_Region_Mobility_Report.csv',
 '2022_ES_Region_Mobility_Report.csv']

In [3]:
# Creating a dataframe for each file, and storing it in a list

mobility_dfs = []
for i in range(len(files_desired)):
    df = pd.read_csv(files_desired[i])  # Creation of dataframe for each file
    df = df[pd.isna(df['sub_region_1'])]  # Obtaining only the general data for Spain (no subregions)
    mobility_dfs.append(df)

In [4]:
# Joining the arrays in an unique one

join_array = np.concatenate((mobility_dfs[0], mobility_dfs[1], mobility_dfs[2]), axis=0)
join_array.shape, join_array[0], join_array[-1]

((770, 15),
 array(['ES', 'Spain', nan, nan, nan, nan, nan,
        'ChIJi7xhMnjjQgwR7KNoB5Qs7KY', '2020-02-15', 2.0, -1.0, 26.0, 8.0,
        0.0, -2.0], dtype=object),
 array(['ES', 'Spain', nan, nan, nan, nan, nan,
        'ChIJi7xhMnjjQgwR7KNoB5Qs7KY', '2022-03-25', -22, 4.0, -7, -15.0,
        -11, 4.0], dtype=object))

In [5]:
# Creating the dataframe

labels = df.columns.values  # Column names
join_df = pd.DataFrame(join_array, columns = labels)
join_df

country_region_code country_region sub_region_1 sub_region_2 metro_area  \
0                    ES          Spain          NaN          NaN        NaN   
1                    ES          Spain          NaN          NaN        NaN   
2                    ES          Spain          NaN          NaN        NaN   
3                    ES          Spain          NaN          NaN        NaN   
4                    ES          Spain          NaN          NaN        NaN   
..                  ...            ...          ...          ...        ...   
765                  ES          Spain          NaN          NaN        NaN   
766                  ES          Spain          NaN          NaN        NaN   
767                  ES          Spain          NaN          NaN        NaN   
768                  ES          Spain          NaN          NaN        NaN   
769                  ES          Spain          NaN          NaN        NaN   

    iso_3166_2_code census_fips_code                     place_id        date  \
0               NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2020-02-15   
1               NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2020-02-16   
2               NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2020-02-17   
3               NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2020-02-18   
4               NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2020-02-19   
..              ...              ...                          ...         ...   
765             NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2022-03-21   
766             NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2022-03-22   
767             NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2022-03-23   
768             NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2022-03-24   
769             NaN              NaN  ChIJi7xhMnjjQgwR7KNoB5Qs7KY  2022-03-25   

    retail_and_recreation_percent_change_from_baseline  \
0                                                    2   
1                                                    2   
2                                                    0   
3                                                   -2   
4                                                    0   
..                                                 ...   
765                                                -23   
766                                                -23   
767                                                -23   
768                                                -22   
769                                                -22   

    grocery_and_pharmacy_percent_change_from_baseline  \
0                                                  -1   
1                                                   3   
2                                                   1   
3                                                   0   
4                                                   1   
..                                                ...   
765                                                 3   
766                                                 6   
767                                                 6   
768                                                 5   
769                                                 4   

    parks_percent_change_from_baseline  \
0                                   26   
1                                   13   
2                                    9   
3                                    5   
4                                   11   
..                                 ...   
765                                 -8   
766                                 -8   
767                                 -9   
768                                 -8   
769                                 -7   

    transit_stations_percent_change_from_baseline  \
0                                               8   
1                                               5   
2                                   

In [6]:
# Dataframe without empty columns

join_df = join_df.dropna(axis=1)
join_df

country_region_code country_region                     place_id  \
0                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
1                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
2                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
3                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
4                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
..                  ...            ...                          ...   
765                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
766                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
767                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
768                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
769                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   

           date retail_and_recreation_percent_change_from_baseline  \
0    2020-02-15                                                  2   
1    2020-02-16                                                  2   
2    2020-02-17                                                  0   
3    2020-02-18                                                 -2   
4    2020-02-19                                                  0   
..          ...                                                ...   
765  2022-03-21                                                -23   
766  2022-03-22                                                -23   
767  2022-03-23                                                -23   
768  2022-03-24                                                -22   
769  2022-03-25                                                -22   

    grocery_and_pharmacy_percent_change_from_baseline  \
0                                                  -1   
1                                                   3   
2                                                   1   
3                                                   0   
4                                                   1   
..                                                ...   
765                                                 3   
766                                                 6   
767                                                 6   
768                                                 5   
769                                                 4   

    parks_percent_change_from_baseline  \
0                                   26   
1                                   13   
2                                    9   
3                                    5   
4                                   11   
..                                 ...   
765                                 -8   
766                                 -8   
767                                 -9   
768                                 -8   
769                                 -7   

    transit_stations_percent_change_from_baseline  \
0                                               8   
1                                               5   
2                                               3   
3                                               4   
4                                               2   
..                                            ...   
765                                           -15   
766                                           -15   
767                                           -17   
768                                           -16   
769                                           -15   

    workplaces_percent_change_from_baseline  \
0                                         0   
1                                        -1   
2                                         3   
3                                         3   
4                                         3   
..                                      ...   
765                                     -11   
766                                     -10   
767                                     -11   
768          

In [7]:
# Obtaining every individual class of mobility rate value

retail = join_df.values[:,4]
grocery = join_df.values[:,5]
parks = join_df.values[:,6]
transit = join_df.values[:,7]
workplaces = join_df.values[:,8]
residential = join_df.values[:,9]

retail[0:5], grocery[0:5], parks[0:5], transit[0:5], workplaces[0:5], residential[0:5]

(array([2.0, 2.0, 0.0, -2.0, 0.0], dtype=object),
 array([-1.0, 3.0, 1.0, 0.0, 1.0], dtype=object),
 array([26.0, 13.0, 9.0, 5.0, 11.0], dtype=object),
 array([8.0, 5.0, 3.0, 4.0, 2.0], dtype=object),
 array([0.0, -1.0, 3.0, 3.0, 3.0], dtype=object),
 array([-2.0, -2.0, -1.0, 0.0, -1.0], dtype=object))

In [8]:
# Obtaining the average mobility rate

average_mobility = np.empty(shape=(len(retail)))

for i in range(len(retail)):
    mean = (retail[i]+grocery[i]+parks[i]+transit[i]+workplaces[i]+residential[i])/6
    average_mobility[i] = mean  # Percentage values

average_mobility.shape, average_mobility[0:5]

((770,), array([5.5       , 3.33333333, 2.5       , 1.66666667, 2.66666667]))

In [9]:
# Creating two new columns with the average mobility rate (percentage and ratio values)

join_df.insert(10, column='average_perc', value = average_mobility)
join_df.insert(11, column='average_rate', value = average_mobility/100)

join_df

country_region_code country_region                     place_id  \
0                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
1                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
2                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
3                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
4                    ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
..                  ...            ...                          ...   
765                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
766                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
767                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
768                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   
769                  ES          Spain  ChIJi7xhMnjjQgwR7KNoB5Qs7KY   

           date retail_and_recreation_percent_change_from_baseline  \
0    2020-02-15                                                  2   
1    2020-02-16                                                  2   
2    2020-02-17                                                  0   
3    2020-02-18                                                 -2   
4    2020-02-19                                                  0   
..          ...                                                ...   
765  2022-03-21                                                -23   
766  2022-03-22                                                -23   
767  2022-03-23                                                -23   
768  2022-03-24                                                -22   
769  2022-03-25                                                -22   

    grocery_and_pharmacy_percent_change_from_baseline  \
0                                                  -1   
1                                                   3   
2                                                   1   
3                                                   0   
4                                                   1   
..                                                ...   
765                                                 3   
766                                                 6   
767                                                 6   
768                                                 5   
769                                                 4   

    parks_percent_change_from_baseline  \
0                                   26   
1                                   13   
2                                    9   
3                                    5   
4                                   11   
..                                 ...   
765                                 -8   
766                                 -8   
767                                 -9   
768                                 -8   
769                                 -7   

    transit_stations_percent_change_from_baseline  \
0                                               8   
1                                               5   
2                                               3   
3                                               4   
4                                               2   
..                                            ...   
765                                           -15   
766                                           -15   
767                                           -17   
768                                           -16   
769                                           -15   

    workplaces_percent_change_from_baseline  \
0                                         0   
1                                        -1   
2                                         3   
3                                         3   
4                                         3   
..                                      ...   
765                                     -11   
766                                     -10   
767                                     -11   
768          

In [10]:
# Export dataframe to a csv file

from pathlib import Path  
filepath = Path('ES_Mobility_Report_Join.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
join_df.to_csv(filepath, index=False)

In [11]:
"""
# Export dataframe to a xlsx file

from pathlib import Path  
filepath = Path('ES_Mobility_Report_Join.xlsx')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
join_df.to_excel(filepath, index=False)
"""

"\n# Export dataframe to a xlsx file\n\nfrom pathlib import Path  \nfilepath = Path('ES_Mobility_Report_Join.xlsx')  \nfilepath.parent.mkdir(parents=True, exist_ok=True)  \njoin_df.to_excel(filepath, index=False)\n"